### ISSUE TITLE
find bug

### ISSUE THREAD

**Issue by viastronger** [jridgewell/gen-mapping#16] opened 2024-12-10 08:24 UTC
last version have a bug, not dist

**Comment by ItsMeKevin1227** [comment] 2024-12-10 08:28
I have the same issue here.

**Comment by TechPrivacyLab** [comment] 2024-12-10 08:33
Already fixed: https://github.com/jridgewell/gen-mapping/issues/14#issuecomment-2530760200

**Comment by vrajpal-jhala** [comment] 2024-12-10 08:33
Duplicate of #14

**Comment by jridgewell** [comment] 2024-12-10 08:35
v0.3.7 is published now.

**Comment by viastronger** [comment] 2024-12-10 08:35
> Duplicate of #14

ok,thank you

**Closed by jridgewell** 2024-12-10 08:35 UTC
