### ISSUE TITLE
@jridgewell/gen-mapping error

### ISSUE THREAD

**Issue by chuxin-cs** [jridgewell/gen-mapping#18] opened 2024-12-10 08:30 UTC
![image](https://github.com/user-attachments/assets/31b0183a-2763-4d7c-9032-2e80cb50fc9b)

@jridgewell/gen-mapping error

**Comment by YiGuaIn** [comment] 2024-12-10 08:32
什么情况，所有项目都打包不了

**Comment by vrajpal-jhala** [comment] 2024-12-10 08:33
Maybe duplicate of #14

**Comment by jridgewell** [comment] 2024-12-10 08:35
v0.3.7 is published now.

**Closed by jridgewell** 2024-12-10 08:35 UTC
