### ISSUE TITLE
@jridgewell/gen-mapping 0.3.5 bug，How to make corrections, thank you for your guidance

### ISSUE THREAD

**Issue by tw-towey** [jridgewell/gen-mapping#17] opened 2024-12-10 08:28 UTC
![image](https://github.com/user-attachments/assets/7e7d224e-3b5c-4bb7-8f93-0b6604f798a6)

**Comment by vrajpal-jhala** [comment] 2024-12-10 08:33
Maybe duplicate of #14

**Comment by TechPrivacyLab** [comment] 2024-12-10 08:33
Already fixed: https://github.com/jridgewell/gen-mapping/issues/14#issuecomment-2530760200

**Comment by jridgewell** [comment] 2024-12-10 08:35
v0.3.7 is published now.

**Closed by jridgewell** 2024-12-10 08:35 UTC
